name: buyer_app
description: GOGOMARKET Buyer Application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../../packages/core
  ui_kit:
    path: ../../packages/ui_kit
  network:
    path: ../../packages/network
  go_router: ^13.2.0
  flutter_riverpod: ^2.4.10
  riverpod: ^2.4.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mocktail: ^1.0.3
  flutter_native_splash: ^2.4.7

flutter:
  uses-material-design: true
