name: core
description: Shared core logic, models, and constants for GOGOMARKET apps.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.7.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  easy_localization: ^3.0.7

dev_dependencies:
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^8.0.0
